### ISSUE TITLE
coverage is 69%, but should be 90% (config)

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.ZMySQLDA#25]
When I run coverage on my laptop, I get the following...

```
❯ tox -epy27,py38,coverage
Coverage failure: total of 69.55 is less than fail-under=90.00
```

**Comment by dataflake** [comment]
You must have a MySQL instance running and set up right. See https://github.com/zopefoundation/Products.ZMySQLDA/blob/master/docs/development.rst#running-the-functional-tests.
