### ISSUE TITLE
NameError: name '_mysql' is not defined after mac OS upgrade to Catalina

### ISSUE THREAD

**Issue by gpzope** [zopefoundation/Products.ZMySQLDA#27]
### What I did:

I just upgrade my mac to Catalina and Zope5.3 wouldn't start showing this error: 

/Applications/zope53/eggs/mysqlclient-2.0.3-py3.7-macosx-10.9-x86_64.egg/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined

Before the upgrade I had no problems.
I didn't make any change to zope or to MySql

MySql is up and running regularly:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 9
Server version: 8.0.13 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 

### What version of Python and Zope/Addons I am using:

Mac OS Catalina, Python 3.9.0, Zope5.3

Thanks for your help,

gipi

**Comment by ale-rt** [comment]
From the description it looks like you are using mysqlclient-2.0.3-py3.7-macosx-10.9-x86_64.egg on Python 3.9.
Was that the result of a buildout run?
If yes try to add to some of your cfgs `abi-tag-eggs = true`.


See https://www.buildout.org/en/latest/topics/optimizing.html#optimizing-buildouts-with-shared-eggs-and-download-caches

**Comment by gpzope** [comment]
> From the description it looks like you are using mysqlclient-2.0.3-py3.7-macosx-10.9-x86_64.egg on Python 3.9. Was that the result of a buildout run? If yes try to add to some of your cfgs `abi-tag-eggs = true`.
> 
> See https://www.buildout.org/en/latest/topics/optimizing.html#optimizing-buildouts-with-shared-eggs-and-download-caches

Here it is:
$ ./bin/buildout
Updating zopescripts.
Getting distribution for 'Products.PluggableAuthService'.
Got Products.PluggableAuthService 2.7.0.
Getting distribution for 'Pillow'.
Got Pillow 9.0.1.
Getting distribution for 'psutil'.
Got psutil 5.9.0.
Getting distribution for 'mysqlclient'.
mysql_config --version
['8.0.13']
mysql_config --libs
['-L/usr/local/mysql/lib', '-lmysqlclient', '-lssl', '-lcrypto']
mysql_config --cflags
['-I/usr/local/mysql/include']
ext_options:
  library_dirs: ['/usr/local/mysql/lib']
  libraries: ['mysqlclient']
  extra_compile_args: ['-std=c99']
  extra_link_args: []
  include_dirs: ['/usr/local/mysql/include']
  extra_objects: []
  define_macros: [('version_info', "(2,1,0,'final',0)"), ('__version__', '2.1.0')]
zip_safe flag not set; analyzing archive contents...
MySQLdb.__pycache__.__init__.cpython-37: module references __file__
MySQLdb.__pycache__._mysql.cpython-37: module references __file__
Got mysqlclient 2.1.0.
Getting distribution for 'Products.GenericSetup>=2.1.2'.
Got Products.GenericSetup 2.1.5.
Getting distribution for 'SoupSieve>=1.9.0'.
Got soupsieve 2.3.1.
Getting distribution for 'pycparser'.
Got pycparser 2.21.
Generated script '/Applications/zope53/bin/addzopeuser'.
Generated script '/Applications/zope53/bin/mkwsgiinstance'.
Generated script '/Applications/zope53/bin/runwsgi'.
Generated script '/Applications/zope53/bin/zconsole'.
Generated interpreter '/Applications/zope53/bin/zopepy'.

By "cfgs" you mean zope.conf?

Thanks!

**Comment by ale-rt** [comment]
The buildout.cfg or the cfgs it extends

**Comment by gpzope** [comment]
> The buildout.cfg or the cfgs it extends

Ok, now I add abi-tag-eggs = true to the file buildout .cfg

$ ./bin/buildout 
Uninstalling zopescripts.
Installing zopescripts.
Generated script '/Applications/zope53/bin/addzopeuser'.
Generated script '/Applications/zope53/bin/mkwsgiinstance'.
Generated script '/Applications/zope53/bin/runwsgi'.
Generated script '/Applications/zope53/bin/zconsole'.
Generated interpreter '/Applications/zope53/bin/zopepy'.

If I start zope I get the same error.

**Comment by d-maurer** [comment]
gpzope wrote at 2022-2-25 08:19 -0800:
< ...
C extensions for Python often use a name starting with `_`.
Thus, `_mysql` is almost surely the C extension module providing access
to "mysql". Apparently, it has not been build.

Special preconditions are necessary to build C extensions
(usually in the form of the installation of OS level packages).
Major OS upgrades may cause that some preconditions are no longer met.

`Products.ZMySQLDA` is not responsible for the building of
`_mysql` (I do not know which package is responsible, maybe
`mysqlclient`). Thus, your bug report targets not the best
possible package.

Once you have found the package supposed to build `mysql`
(it might be an OS level package), carefully read its installation
instructions and verify that all preconditions are met.

**Comment by dataflake** [comment]
You claim to use Python 3.9 in your error description but the egg paths are for Python 3.7. That cannot work. When you make a major Python upgrade you must completely rebuild your Zope buildout, including the script `bin/buildout` itself, which apparently still thinks it's using Python 3.7.

I can't tell how you created that deployment in the first place, but it looks like you have a buildout root folder at `/Applications/zope53`. If I were you I would go into that folder and delete several items, including the `bin` and `eggs` folders and the file `.installed.cfg`. Then I would initialize a new virtual environment using Python 3.9, like `python3.9 -m venv .` (don't overlook the `.`), followed by `bin/pip install -U pip wheel` and `bin/pip install -U "setuptools<52" zc.buildout`. When that is done run `bin/buildout` again. The buildout will retrieve and/or build eggs and wheels for Python 3.9.

**Comment by gpzope** [comment]
I apologize for the typo, I used Python 3.7.

**Comment by dataflake** [comment]
If this solved your issue please close it here.

**Comment by gpzope** [comment]
I will try again starting with a new fresh version of zope5.5.

**Comment by gpzope** [comment]
Ok, the magic line to add to the .bash_profile: export DYLD_LIBRARY_PATH="/usr/local/mysql/lib:$PATH"
took care of it. I guess we can close it now. Thanks.

**Comment by dataflake** [comment]
Side note: I'm surprised you needed to set that variable. I have done development for this package on subsequent MacOS versions with MariaDB installed via Homebrew for several years and never had to set that library path.

**Comment by dataflake** [comment]
P.S.: I just noticed that your install path for MySQL is unusual. Homebrew uses standard library folders like `/usr/local/lib` on x86_64 for that, and those are included when searching for libraries. So that's where the issue is.

**Comment by gpzope** [comment]
Thanks Jens, I appreciate your will to take care of this. If I remember well, I started to have this issue since my upgrade to OS Catalina (10.17.7). I know, it's quite a mess now. Well, as soon as I have a minute I will go back to it and follow your directions (they may be good for installing Pillow as well). Thanks again.

**Comment by dataflake** [comment]
Just FYI, Pillow will also be easier to install if you use Homebrew for adding missing graphics libraries.

**Comment by gpzope** [comment]
After I run your line bin/pip install -U "setuptools<52" zc.buildout and follow your direction I was also able to install Pillow just listing it in the buildout.cfg. But please help me to understand: how do you know for instance about this downgrade of setuptools? Or better, where do I go (and where all the people like me go) to learn all of this tids and bits without bugging people like you?  Thank You.

**Comment by gpzope** [comment]
I don't have any idea, sorry. How do I check it? :-(

**Comment by dataflake** [comment]
@gpzope The setuptools pin prevents compatibility issues with `zc.buildout`. I have not analyzed what those are and cannot point you to specific documentation, it's just something I have seen others do so it has become the safe thing to do for me.

Your desire to have everything documented starting with the birds and the bees, so to speak, is understandable but it cannot be fulfilled. The developer community around Zope simply doesn't have the resources to offer documentation down to that detailed level. My apologies.
